-- versao 02
SELECT COUNT(*) FROM
(SELECT TAB_OCORRENCIAS.DEM_EX, LPAD(TAB_OCORRENCIAS.DEM_CD, 3, '0') AS DEM_CD FROM
	(SELECT DEM_EX, DEM_CD, COUNT(*) AS OCORRENCIAS
	FROM DEMANDA_TRAM
	WHERE 
		(DTM_CD_SETOR_ORIGEM = 2 AND DTM_CD_SETOR_DESTINO = 3) -- UNCT PARA ATJA
        OR (DTM_CD_SETOR_ORIGEM = 3 AND DTM_CD_SETOR_DESTINO = 2) -- ATJA PARA UNCT
        OR (DTM_CD_SETOR_ORIGEM = 2 AND DTM_CD_SETOR_DESTINO = 2 AND (CD_USUARIO_INCL = 23 OR CD_USUARIO_INCL = 1)) -- UNCT PARA UNCT com ATJA (daniel 1 e alfredo 23) tramitando
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD
    ) TAB_OCORRENCIAS
    
    WHERE OCORRENCIAS > 2 -- QUANDO A ATJA DEVOLVEU MAIS DE UMA VEZ A UNCT
    AND DEM_EX = 2020
) TAB_EXTERNA
-- DEM 4, 2020 UM BOM EXEMPLO

-- versao 01
SELECT COUNT(*) FROM
-- (SELECT TAB_DEMANDA_TRAM_MIN.DEM_EX, TAB_DEMANDA_TRAM_MIN.DEM_CD, MINIMO, MAXIMO FROM
(SELECT TAB_DEMANDA_TRAM_MIN.DEM_EX, LPAD(TAB_DEMANDA_TRAM_MIN.DEM_CD, 3, '0') FROM
	(SELECT DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD, MIN(DTM_SQ) AS MINIMO
	FROM DEMANDA_TRAM
	WHERE DTM_CD_SETOR_ORIGEM = 3 -- ATJA
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD) TAB_DEMANDA_TRAM_MIN

	LEFT JOIN
	(SELECT DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD, MAX(DTM_SQ) AS MAXIMO FROM DEMANDA_TRAM
	WHERE 
		DTM_CD_SETOR_DESTINO = 3 -- ATJA
        OR (DTM_CD_SETOR_DESTINO = 2 AND DTM_CD_SETOR_ORIGEM <> 3 AND (CD_USUARIO_INCL = 23 OR CD_USUARIO_INCL = 1)) 
        -- DESTINO UNCT POREM TRAMITADO PELOS ASSESSORES (daniel 1 e alfredo 23), QUE TAMBEM TRAMITAM PELA UNCT (tramitando por outros setores que nao ATJA)
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD) TAB_DEMANDA_TRAM_MAX
	ON TAB_DEMANDA_TRAM_MIN.DEM_EX = TAB_DEMANDA_TRAM_MAX.DEM_EX
	AND TAB_DEMANDA_TRAM_MIN.DEM_CD = TAB_DEMANDA_TRAM_MAX.DEM_CD
WHERE 
EXISTS (SELECT 'X' FROM   DEMANDA_TRAM
                WHERE  (DTM_CD_SETOR_ORIGEM = 2 OR DTM_CD_SETOR_DESTINO = 2)
                     AND DTM_SQ BETWEEN MINIMO AND MAXIMO
                     AND TAB_DEMANDA_TRAM_MIN.DEM_EX = DEMANDA_TRAM.DEM_EX
                     AND TAB_DEMANDA_TRAM_MIN.DEM_CD = DEMANDA_TRAM.DEM_CD)

AND TAB_DEMANDA_TRAM_MIN.DEM_EX = 2020 
ORDER BY LPAD(TAB_DEMANDA_TRAM_MIN.DEM_CD, 3, '0')) TAB_FIM
-- DEM 4, 2020 UM BOM EXEMPLO