-- versao 03
-- consultar as demandas enviadas pela UNCT a ATJa que tenham mais de uma ida à ATJA (retorno)
SELECT COUNT(*) FROM
(SELECT TAB_OCORRENCIAS.DEM_EX, LPAD(TAB_OCORRENCIAS.DEM_CD, 3, '0') AS DEM_CD FROM
	(SELECT DEM_EX, DEM_CD, COUNT(*) AS OCORRENCIAS
	FROM DEMANDA_TRAM
	WHERE 
		DEM_EX = 2019
		-- AND DEM_CD = 198
        AND DTM_CD_SETOR_DESTINO = 2 -- destino EH ATJA
        AND DTM_CD_SETOR_DESTINO <> DTM_CD_SETOR_ORIGEM -- quantas vezes foi enviada para a ATJA mas nao pela ATJA
		AND EXISTS (SELECT 'X' FROM   DEMANDA_TRAM DEMANDA_TRAM_INTERNA
					WHERE  (DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_ORIGEM = 2 AND DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_DESTINO = 3) -- FOI ENVIADA DA UNCT PRA ATJA INICIALMENTE
						AND DEMANDA_TRAM_INTERNA.DEM_EX = DEMANDA_TRAM.DEM_EX
						AND DEMANDA_TRAM_INTERNA.DEM_CD = DEMANDA_TRAM.DEM_CD
                        AND DEMANDA_TRAM_INTERNA.DTM_SQ <= DEMANDA_TRAM.DTM_SQ) -- O ENVIO DA UNCT PRA ATJA OCORREU ANTES DAS OUTRAS OCORRENCIAS (permite dizer que trata-se de uma demanda da unct pra atja)        
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD
    ) TAB_OCORRENCIAS
    
    WHERE OCORRENCIAS >= 2 -- QUANDO A ATJA DEVOLVEU MAIS DE UMA VEZ A UNCT
    
) TAB_EXTERNA

-- TOTAL DE DEMANDAS 
SELECT COUNT(*) FROM
	(SELECT DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD FROM DEMANDA_TRAM
    INNER JOIN DEMANDA
    ON DEMANDA.DEM_EX = DEMANDA_TRAM.DEM_EX
    AND DEMANDA.DEM_CD = DEMANDA_TRAM.DEM_CD
	WHERE 
		DEMANDA_TRAM.DEM_EX = 2020
        AND IN_DESATIVADO = 'N'
		-- AND DEM_CD = 198
		AND EXISTS (SELECT 'X' FROM   DEMANDA_TRAM DEMANDA_TRAM_INTERNA
					WHERE  (DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_ORIGEM = 2 AND DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_DESTINO = 3
							OR DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_ORIGEM = 3 AND DEMANDA_TRAM_INTERNA.DTM_CD_SETOR_DESTINO = 2)						
						AND DEMANDA_TRAM_INTERNA.DEM_EX = DEMANDA_TRAM.DEM_EX
						AND DEMANDA_TRAM_INTERNA.DEM_CD = DEMANDA_TRAM.DEM_CD)
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD
    ) TAB_OCORRENCIAS    
-- DEM 4, 2020 UM BOM EXEMPLO


-- versao 02
SELECT COUNT(*) FROM
(SELECT TAB_OCORRENCIAS.DEM_EX, LPAD(TAB_OCORRENCIAS.DEM_CD, 3, '0') AS DEM_CD FROM
	(SELECT DEM_EX, DEM_CD, COUNT(*) AS OCORRENCIAS
	FROM DEMANDA_TRAM
	WHERE 
		(DTM_CD_SETOR_ORIGEM = 2 AND DTM_CD_SETOR_DESTINO = 3) -- UNCT PARA ATJA
        OR (DTM_CD_SETOR_ORIGEM = 3 AND DTM_CD_SETOR_DESTINO = 2) -- ATJA PARA UNCT
        OR (DTM_CD_SETOR_ORIGEM = 2 AND DTM_CD_SETOR_DESTINO = 2 AND (CD_USUARIO_INCL = 23 OR CD_USUARIO_INCL = 1)) -- UNCT PARA UNCT com ATJA (daniel 1 e alfredo 23) tramitando
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD
    ) TAB_OCORRENCIAS
    
    WHERE OCORRENCIAS > 2 -- QUANDO A ATJA DEVOLVEU MAIS DE UMA VEZ A UNCT
    AND DEM_EX = 2020
) TAB_EXTERNA
-- DEM 4, 2020 UM BOM EXEMPLO

-- versao 01
SELECT COUNT(*) FROM
-- (SELECT TAB_DEMANDA_TRAM_MIN.DEM_EX, TAB_DEMANDA_TRAM_MIN.DEM_CD, MINIMO, MAXIMO FROM
(SELECT TAB_DEMANDA_TRAM_MIN.DEM_EX, LPAD(TAB_DEMANDA_TRAM_MIN.DEM_CD, 3, '0') FROM
	(SELECT DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD, MIN(DTM_SQ) AS MINIMO
	FROM DEMANDA_TRAM
	WHERE DTM_CD_SETOR_ORIGEM = 3 -- ATJA
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD) TAB_DEMANDA_TRAM_MIN

	LEFT JOIN
	(SELECT DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD, MAX(DTM_SQ) AS MAXIMO FROM DEMANDA_TRAM
	WHERE 
		DTM_CD_SETOR_DESTINO = 3 -- ATJA
        OR (DTM_CD_SETOR_DESTINO = 2 AND DTM_CD_SETOR_ORIGEM <> 3 AND (CD_USUARIO_INCL = 23 OR CD_USUARIO_INCL = 1)) 
        -- DESTINO UNCT POREM TRAMITADO PELOS ASSESSORES (daniel 1 e alfredo 23), QUE TAMBEM TRAMITAM PELA UNCT (tramitando por outros setores que nao ATJA)
	GROUP BY DEMANDA_TRAM.DEM_EX, DEMANDA_TRAM.DEM_CD) TAB_DEMANDA_TRAM_MAX
	ON TAB_DEMANDA_TRAM_MIN.DEM_EX = TAB_DEMANDA_TRAM_MAX.DEM_EX
	AND TAB_DEMANDA_TRAM_MIN.DEM_CD = TAB_DEMANDA_TRAM_MAX.DEM_CD
WHERE 
EXISTS (SELECT 'X' FROM   DEMANDA_TRAM
                WHERE  (DTM_CD_SETOR_ORIGEM = 2 OR DTM_CD_SETOR_DESTINO = 2)
                     AND DTM_SQ BETWEEN MINIMO AND MAXIMO
                     AND TAB_DEMANDA_TRAM_MIN.DEM_EX = DEMANDA_TRAM.DEM_EX
                     AND TAB_DEMANDA_TRAM_MIN.DEM_CD = DEMANDA_TRAM.DEM_CD)

AND TAB_DEMANDA_TRAM_MIN.DEM_EX = 2020 
ORDER BY LPAD(TAB_DEMANDA_TRAM_MIN.DEM_CD, 3, '0')) TAB_FIM
-- DEM 4, 2020 UM BOM EXEMPLO